import { UserRole } from "../../../generated/prisma/client.js";
import {
	ALL_PERMISSION_VALUES,
	PERMISSION_KEYS,
	type PermissionKey,
} from "./permission-keys.js";

/** Static permissions per role (replaces DB role_permissions). */
export const ROLE_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
	[UserRole.ADMIN]: [...ALL_PERMISSION_VALUES],
	[UserRole.SELLER]: [PERMISSION_KEYS.PRODUCTS_READ],
	[UserRole.INVENTORY_MANAGER]: [
		PERMISSION_KEYS.CATEGORIES_READ,
		PERMISSION_KEYS.CATEGORIES_CREATE,
		PERMISSION_KEYS.CATEGORIES_UPDATE,
		PERMISSION_KEYS.CATEGORIES_DEACTIVATE,
		PERMISSION_KEYS.CATEGORIES_REACTIVATE,
		PERMISSION_KEYS.BRANDS_READ,
		PERMISSION_KEYS.BRANDS_CREATE,
		PERMISSION_KEYS.BRANDS_UPDATE,
		PERMISSION_KEYS.BRANDS_DEACTIVATE,
		PERMISSION_KEYS.BRANDS_REACTIVATE,
		PERMISSION_KEYS.SUPPLIERS_READ,
		PERMISSION_KEYS.SUPPLIERS_CREATE,
		PERMISSION_KEYS.SUPPLIERS_UPDATE,
		PERMISSION_KEYS.SUPPLIERS_DEACTIVATE,
		PERMISSION_KEYS.SUPPLIERS_REACTIVATE,
		PERMISSION_KEYS.PRODUCTS_READ,
		PERMISSION_KEYS.PRODUCTS_CREATE,
		PERMISSION_KEYS.PRODUCTS_UPDATE,
		PERMISSION_KEYS.PRODUCTS_DEACTIVATE,
		PERMISSION_KEYS.PRODUCTS_REACTIVATE,
		PERMISSION_KEYS.PRODUCTS_UPLOAD,
	],
	[UserRole.DISPATCH_MANAGER]: [],
	[UserRole.OWNER_MANAGER]: [
		PERMISSION_KEYS.USERS_READ,
		PERMISSION_KEYS.CATEGORIES_READ,
		PERMISSION_KEYS.SUPPLIERS_READ,
		PERMISSION_KEYS.PRODUCTS_READ,
	],
};

export function getPermissionsForRole(role: UserRole): PermissionKey[] {
	return ROLE_PERMISSIONS[role] ?? [];
}
